// The rules mimic the behavior of BehavePlus Version 6-beta
export const BehavePlusRules = {
    surfaceFire: [
        'if surfaceFireModule active',
            // Start at the module at the end of the chain and move to the start,
            // as the latter modules always 'appy' the modules before them.
            // fireVectorModule will 'apply' fireSize, fireBehavior, fuelIgnition, fuelBed, fuelModel
            'if surfaceFireVectorModule active',
                'apply fireVector',
            'elseif surfaceFireSizeModule active',
                'apply fireSize',
            'elseif surfaceFireBehaviorModule active',
                'apply fireBehaviors',
            'elseif surfaceFuelIgnitionModule active',
                'apply fuelIgnitions',
            'elseif surfaceFuelBedModule active',
                'apply fuelBeds',
            'elseif surfaceFuelModelModule active',
                'apply fuelModels',
            'endif',
        'elseif fireSizeModule active',     // stand-alone fire ellipse/size module
            'apply fireSize',
        'elseif fireVectorModule active',     // stand-alone fire ellipse/size module
            'apply fireVector',
        'elseif activeCrownFireModule active',  // stand-alone crown fire module
            'apply activeCrownFire',
        'endif',
    ],

    activeCrownFire: [  // stand-alone
        'call makeActiveCrownFireFuelBed',
        // Even the stand-alone crown fire has to have a surface fuel and fire for HPUA
        'apply fuelBeds',
        'apply fuelIgnitions',
        'call makeActiveCrownFireFuelIgnition',
        'apply windDirection',
        'apply windSpeed',
        'call makeActiveCrownFireBehavior',
    ],
    deadFuelMoisture: [
        'if deadFuelMoistureFrom Particles',
            'each fuelMoistureDead100h',
            'each fuelMoistureDead10h',
            'each fuelMoistureDead1h',
        'elseif deadFuelMoistureFrom Category',
            'each fuelMoistureDeadCategory',
            'call updateDeadFuelMoistureFromCategory',
        'endif',
    ],
    fuelCatalog: [
        // create the fuelCatalog and update its curingClasses and moistureClasses
        'call makeFuelCatalog',
        'if activeCrownFireModule active',
            // create the activeCrownFire and its fuelModel and fuelBed
            'call makeActiveCrownFireFuelBed',
        'endif',
    ],
    fuelCuring: [
        'if fuelCuringFrom input',
            'each fuelCuringCuredHerb',
            'each fuelCuringCuredCheatgrass',
        'elseif fuelCuringFrom LiveHerbMoisture',
            'each fuelMoistureLiveHerb',
            'call updateFuelCuringFromLiveHerbMoisture',
        'endif',
    ],
    fuelModels: [
        'apply fuelCatalog',
        'if fuelModels one',
            'each fuelKeyOne',
        'elseif fuelModels two',
            'each fuelKeyOne',
            'each fuelKeyTwo',
        'endif',
        // create new fuelModels = {one, two, curingClasses, moistureClasses}
        'call makeFuelModelsFromFuelKeys',
    ],
    fuelBeds: [
        'apply fuelModels',
        'apply fuelCuring',
        // create new fuelBeds = {one, two}
        'call makeFuelBedsFromFuelModelsAndCuring'
    ],
    fuelIgnitions: [
        'apply fuelBeds',
        'apply liveFuelMoisture',
        'apply deadFuelMoisture',
        // create new fuelIgnitions = {one, two}
        'call makeFuelIgnitionsFromFuelMoisture',
        'if activeCrownFireModule active',
            'call makeActiveCrownFireFuelIgnition',
        'endif',
    ],
    fireBehaviors: [
        'apply fuelBeds',
        'apply fuelIgnitions',
        'apply slopeDirection',
        'apply windDirection',
        'apply slopeSteepness',
        'apply midflameWindSpeed',
        'call makeFireBehavior',
        'if activeCrownFireModule active',
            'apply windSpeed',
            'call makeActiveCrownFireBehavior',
        'endif',
    ],
    fireEllipse: [  // or 'fireShape'?
        'if surfaceFireModule active', // if linked to surface
            'apply fireBehaviors',
            // the method should update fireEllipse vectorProp where
            // vector = 'head', 'back', 'right', and 'left'
            // prop = 'spreadRate', 'bearing', 'angleFromHead'
            'call makeFireEllipseFromSurfaceFire',
        'elseif fireSizeModule active', // if stand-alone
            'each observedHeadSpreadRate',
            'each observedHeadBearing',
            'each observedLengthWidthRatio',
            'each observedFlameLength',
            'call makeFireEllipseFromObservedFire',
        'endif',
    ],
    fireSize: [
        'apply fireEllipse',
        'each ignitionElapsedTime',
        // the method should update fireEllipse update vectorProp where
        // vector = 'head', 'back', 'right', and 'left'
        // prop = 'distance', 'easting', 'northing'
        'call makeFireSizeFromElapsedTime',
        'each ignitionEasting',
        'each ignitionNorthing',
        'call makeFirePositionFromElapsedTime',
    ],
    fireVector: [
        'apply fireSize',
        // Could add a fireVectorBearing config option
        'each fireVectorAngleFromHead',
        'if fireVectorBeta active',
            'call makeFireVectorBeta',
        'endif',
        'if fireVectorBeta6 active',
            'call makeFireVectorBeta6',
        'endif',
        'if fireVectorPsi active',
            'call makeFireVectorPsi',
        'endif',
        'if fireVectorTheta active',
            'call makeFireVectorTheta',
        'endif',
    ],
    liveFuelMoisture: [
        'if liveFuelMoistureFrom Particles',
            'each fuelMoistureLiveStem',
            'each fuelMoistureLiveHerb',
        'elseif liveFuelMoistureFrom Catgeory',
            'each fuelMoisture.liveCategory',
            'call updateLiveFuelMoistureFromCategory',
        'endif',
    ],
    // rule required so fuelCuring can get live herb separate from live stem
    liveFuelMoistureHerb: [
        'if liveFuelMoistureFrom Particles',
            'each fuelMoistureLiveHerb',
        'elseif liveFuelMoistureFrom Catgeory',
            'each fuelMoisture.liveCategory',
            'call updateLiveFuelMoistureFromCategory',
        'endif',
    ],
    midflameWindSpeed: [
        'if midflameWindSpeedFrom input',
            'each midflameWindSpeed',
        'elseif midflameWindSpeedFrom WsrfAnd20ftWind',
            'apply midflameWsrf',
            'apply windSpeed',
            'call updateMidflameWindSpeedFromWsrfAnd20ftWind',
        'endif',
    ],
    midflameWsrf: [
        'if midflameWsrfFrom input',
            'each midflameWsrf',
        'elseif midflameWsrfFrom CanopyAndFuelBed',
            'apply canopyStructure',
            'apply fuelBeds',
            'call updateMidflameWsrfFromCanopyAndFuelBed',
        'endif',
    ],
    canopyStructure: [
        'if canopyStructureFrom HeightBase',
            'each canopyHeight',
            'each canopyBase',
            'call updateCanopyFromHeightBase',
        'elseif canopyStructureFrom HeightLength',
            'each canopyHeight',
            'each canopyLength',
            'call updateCanopyFromHeightLength',
        'elseif canopyStructureFrom HeightRatio',
            'each canopyHeight',
            'each canopyRatio',
            'call updateCanopyFromHeightRatio',
        'elseif canopyStructureFrom LengthBase',
            'each canopyLength',
            'each canopyBase',
            'call updateCanopyFromLengthBase',
        'endif',
    ],
    canopyFuel: [
        'each canopyBulkDensity',
        'each canopyHeatContent',
        'call updateCanopyFuel',
    ],
    slopeDirection: [
        'if slopeDirectionFrom Aspect',
            'each slopeDirectionFromAspect',
            'call updateSlopeDirectionFromAspect',
        'elseif slopeDirectionFrom Upslope',
            'each slopeDirectionFromUpslope',
            'call updateSlopeDirectionFromUpslope',
        'endif',
    ],
    slopeMap: [
        'each slopeMapScale',
        'each slopeMapContourInterval',
        'each slopeMapContoursCrossed',
        'each slopeMapDistance',
        'call updateSlopeMap',
    ],
    slopeSteepness: [
        'if slopeSteepnessFrom Degrees',
            'each slopeSteepnessFromDegrees',
            'call updateSlopeSteepnessFromDegrees',
        'elseif slopeSteepnessFrom Map',
            'apply slopeMap',
            'call updateSlopeSteepnessFromMap',
        'elseif slopeSteepnessFrom Ratio',
            'each slopeSteepnessFromRatio',
            'call updateSlopeSteepnessFromRatio',
        'endif',
    ],
    windDirection: [
        'if windDirectionFrom BearingDegrees',
            'each windDirectionFromBearingDegrees',
            'call updateWindDirectionFromBearingDegrees',
        'elseif windDirectionFrom SourceDegrees',
            'each windDirectionFromSourceDegrees',
            'call updateWindDirectionFromSourceDegrees',
        'elseif windDirectionFrom SourceCompass',
            // N, NNE, NE, ENE, E, ESE, SE, SSE, S, SSW, SW, WSW, W, WNW, NW, NNW
            'each windDirectionFromSourceCompass',
            'call updateWindDirectionFromSourceCompass',
        'endif',
    ],
    windSpeed: [
        'if windSpeedFrom 10m',
            'each windSpeedFrom10m',
            'call updateWindSpeedFrom10m',
        'elseif windSpeedFrom 20ft',
            'each windSpeedFrom20ft',
            'call updateWindSpeedFrom20ft',
        'endif'
    ],
}
