export const WfbxInput = {
    curedHerb: [0.778],
    deadMoistureCategory: [0.1],
    deadMoisture1h: [0.05],
    deadMoisture10h: [0.07],
    deadMoisture100h: [0.09],
    elapsedTime: [60],
    fuelKeyOne: [10],
    fuelKeyTwo: [124],
    liveCurableMoisture: [0.5],
    liveMoistureCategory: [3],
    liveMoistureHerb: [0.5],
    liveMoistureStem: [1.5],
    mapContoursCrossed: [2.5],
    mapDistance: [1000],
    mapContourInterval: [100],
    mapScale: [24000],
    midflameWindSpeed: [880],
    midflameWsrf: [1],
    observedHeadBearing: [0],
    observedHeadSpreadRate: [1],
    observedHeadFlameLength: [1],
    observedLengthWidthRatio: [2],
    slopeUpslope: [0],
    slopeAspect: [180],
    slopeDegrees: [14],
    slopeRatio: [0.25],
    windBearingDegrees: [90],
    windSourceCompass: ['W'],
    windSourceDegrees: [270],
    
}
