export const BehaveConfigs2 = {
    canopyStructureFrom: 'height-base',
    // 'height-length',
    // 'height-ratio',
    // 'length-base',
    fuelCuringFrom: 'estimate', // input
    fuelModels: 'two',  // 'one, two, chaparral, aspen, custom, pg
    moistureDeadFuelFrom: 'particles', // particles
    moistureLiveFuelFrom: 'particles', // particles
    midflameWindSpeedFrom: 'estimate', // input
    midflameWsrfFrom: 'estimate', // input
    slopeDirectionFrom: 'slopeUpslope', // slopeAspect, slopeUpslope
    slopeSteepnessFrom: 'slopeMap', // slopeDegrees, slopeMap, slopeRatio
    windDirectionFrom: 'windSourceCompass',    // windBearingDegrees, windSourceCompass, windSourceDegrees
    windSpeedFrom: 'windSpeed10m', // windSpeed20ft
}

export const BehaveRules2 = {
    canopyBase: ['input'],
    canopyCover: ['input'],
    canopyLength: ['input'],
    canopyHeight: ['input'],
    canopyRatio: ['input'],
    canopyStructure: [
        'if canopyStructureFrom height-base',
            'use canopyHeight',
            'use canopyBase',
            'use canopyCover',
            'call updateFromHeightBase',
        'endif',
        'if canopyStructureFrom height-length',
            'use canopyHeight',
            'use canopyLength',
            'use canopyCover',
            'call updateFromHeightBase',
        'endif',
        'if canopyStructureFrom height-ratio',
            'use canopyHeight',
            'use canopyRatio',
            'use canopyCover',
            'call updateFromHeightBase',
        'endif',
        'if canopyStructureFrom length-base',
            'use canopyLength',
            'use canopyBase',
            'use canopyCover',
            'call updateFromHeightBase',
        'endif',
    ],
    fuelCuring: [
        'use fuelCuringHerb',
        'use fuelCuringCheatgrass'
    ],
    fuelCuringHerb: [
        'if fuelCuringFrom input',
            'input',
        'endif',
        'if fuelCuringFrom estimate',
            'use moistureLiveHerb',
            'call updateFromHerbMoisture',
        'endif'
    ],
    fuelCuringCheatgrass: [
        'if fuelCuringFrom input',
            'input',
        'endif',
        'if fuelCuringFrom estimate',
            'use moistureLiveHerb',
            'call updateFromHerbMoisture',
        'endif'
    ],
    fuelCatalog: [],
    midflameWindSpeed: [
        'if midflameWindSpeedFrom input',
            'input',
        'endif',
        'if midflameWindSpeedFrom estimate',
            'use midflameWsrf',
            'use windSpeed20ft',
            'call updateFrom20ftWsrf',
        'endif',
    ],
    midflameWsrf: [
        'if midflameWsrfFrom input',
            'input',
        'endif',
        'if midflameWsrfFrom estimate',
            'use canopyStructure',
            'use fuelBedOne',
            'call updateFromCanopyFuelBed',
        'endif',
    ],
    moistureDead1h: [
        'if moistureDeadFuelFrom particles',
            'input',
        'endif',
        'if moistureDeadFuelFrom category',
            'use moistureDeadCategory',
            'call updateFromMoistureDeadCategory',
        'endif',
    ],
    moistureDead10h: [
        'if moistureDeadFuelFrom particles',
            'input',
        'endif',
        'if moistureDeadFuelFrom category',
            'use moistureDeadCategory',
            'call updateFromMoistureDeadCategory',
        'endif',
    ],
    moistureDead100h: [
        'if moistureDeadFuelFrom particles',
            'input',
        'endif',
        'if moistureDeadFuelFrom category',
            'use moistureDeadCategory',
            'call updateFromMoistureDeadCategory',
        'endif',
    ],
    moistureDeadCategory: [
        'if moistureDeadFuelFrom category',
            'input',
        'endif',
    ],
    moistureLiveHerb: [
        'if moistureLiveFuelFrom particles',
            'input',
        'endif',
        'if moistureLiveFuelFrom category',
            'use moistureLiveCategory',
            'call updateFromMoistureLiveCategory',
        'endif',
    ],
    moistureLiveStem: [
        'if moistureLiveFuelFrom particles',
            'input',
        'endif',
        'if moistureLiveFuelFrom category',
            'use moistureLiveCategory',
            'call updateFromMoistureLiveCategory',
        'endif',
    ],
    moistureLiveCategory: [
        'if moistureLiveFuelFrom category',
            'input',
        'endif',
    ],
    slopeAspect : [
        'if slopeDirectionFrom slopeAspect',
            'input',
        'endif',
        'if slopeDirectionFrom slopeUpslope',
            'use slopeUpslope',
            'call updateFromSlopeUpslope',
        'endif',
    ],
    mapScale: ['input'],
    mapContourInterval: ['input'],
    mapContoursCrossed: ['input'],
    mapDistance: ['input'],
    slopeMap: [
        'use mapScale',
        'use mapContourInterval',
        'use mapContoursCrossed',
        'use mapDistance',
        'call updateSlopeSteepnessFromMap',
    ],
    slopeUpslope: [
        'if slopeDirectionFrom slopeUpslope',
            'input',
        'endif',
        'if slopeDirectionFrom slopeAspect',
            'use slopeAspect',
            'call updateFromSlopeAspect',
        'endif',
    ],
    slopeDegrees : [
        'if slopeSteepnessFrom slopeDegrees',
            'input',
        'endif',
        'if slopeSteepnessFrom slopeMap',
            'use slopeMap',
            'call updateFromSlopeMap',
        'endif',
        'if slopeSteepnessFrom slopeRatio',
            'use slopeRatio',
            'call updateFromSlopeRatio',
        'endif',
    ],
    slopeRatio: [
        'if slopeSteepnessFrom slopeRatio',
            'input',
        'endif',
        'if slopeSteepnessFrom slopeMap',
            'use slopeMap',
            'call updateFromSlopeMap',
        'endif',
        'if slopeSteepnessFrom slopeDegrees',
            'use slopeDegrees',
            'call updateFromSlopeDegrees',
        'endif',
    ],
    surfaceFireBehavior: [
        'if fuelModels one',
            'use oneFireBehavior',
            'call updateFromOneFuelModel',
        'endif',
        'if fuelModels two',
            'use oneFuelCover',
            'use oneFireBehavior',
            'use twoFireBehavior',
            'call updateFromTwoFuelModels',
        'endif',
    ],
    windBearingDegrees: [
        'if windDirectionFrom windBearingDegrees',
            'input',
        'endif',
        'if windDirectionFrom windSourceCompass',
            'use windSourceCompass',
            'call updateFromWindSourceCompass',
        'endif',
        'if windDirectionFrom windSourceDegrees',
            'use windSourceDegrees',
            'call updateFromWindSourceDegrees',
        'endif',
    ],
    windSourceCompass: ['input'],
    windSourceDegrees : [
        'if windDirectionFrom windSourceDegrees',
            'input',
        'endif',
        'if windDirectionFrom windSourceCompass',
            'use windSourceCompass',
            'call updateFromWindSourceCompass',
        'endif',
        'if winDirectionFrom windBearingDegrees',
            'use windBearingDegrees',
            'call updateFromWindBearingDegrees',
        'endif',
    ],
    windSpeed10m: [
        'if windSpeedFrom windSpeed10m',
            'input',
        'endif',
        'if windSpeedFrom windSpeed20ft',
            'use windSpeed20ft',
            'call updateFromWindSpeed20ft',
        'endif',
    ],
    windSpeed20ft: [
        'if windSpeedFrom windSpeed20ft',
            'input',
        'endif',
        'if windSpeedFrom windSpeed10m',
            'use windSpeed10m',
            'call updateFromWindSpeed10m',
        'endif',
    ],

    fuelCoverOne: ['input'],
    fuelKeyOne: ['input'],
    fuelKeyTwo: ['input'],

    fuelModels: [
        'if fuelModels one',
            'use fuelModelOne',
        'endif',
        'if fuelModels two',
            'use fuelModelOne',
            'use fuelModelTwo',
        'endif',
    ],
    fuelModelOne: [
        'use fuelCatalog',
        'use fuelKeyOne',
        'call updateFromFuelKey',
    ],
    fuelModelTwo: [
        'use fuelCatalog',
        'use fuelKeyTwo',
        'call updateFromFuelKey',
    ],
    fuelBeds: [
        'use fuelModels',
        'if fuelModels one',
            'use fuelBedOne',
        'endif',
        'if fuelModels two',
            'use fuelBedOne',
            'use fuelBedTwo',
        'endif',
    ],
    fuelBedOne: [
        'use fuelModelOne',
        'use fuelCuring',
        'call updateFromFuelModelAndCuring'
    ],
    fuelBedTwo: [
        'use fuelModelTwo',
        'use fuelCuring',
        'call updateFromFuelModelAndCuring'
    ],
    fuelIgnitions: [
        'use fuelBeds',
        'if fuelModels one',
            'use fuelIgnitionOne',
        'endif',
        'if fuelModels two',
            'use fuelIgnitionOne',
            'use fuelIgnitionTwo',
        'endif',
    ],
    fuelIgnitionOne: [
        'use fuelBedOne',
        'use moistureLiveStem',
        'use moistureLiveHerb',
        'use moistureDead100h',
        'use moistureDead10h',
        'use moistureDead1h',
        'call updateFromFuelBedAndMoisture',
    ],
    fuelIgnitionTwo: [
        'use fuelBedOne',
        'use moistureLiveStem',
        'use moistureLiveHerb',
        'use moistureDead100h',
        'use moistureDead10h',
        'use moistureDead1h',
        'call updateFromFuelBedAndMoisture',
    ],
    fireBehavior: [
        'use fuelIgnitions',
        'if fuelModels one',
            'use fireBehaviorlOne',
            'call updateFromOneFuelModel',
        'endif',
        'if fuelModels two',
            'use fireBehaviorOne',
            'use fireBehaviorTwo',
            'call updateFromTwoFuelModels',
        'endif',
    ],
    fireBehaviorOne: [
        'use fuelBedOne',
        'use fuelIgnitionOne',
        'use slopeAspect',
        'use windBearingDegrees',
        'use slopeRatio',
        'use midflameWindSpeed',
        'call update',
    ],
    fireBehaviorTwo: [
        'use fuelBedTwo',
        'use fuelIgnitionTwo',
        'use slopeAspect',
        'use windBearingDegrees',
        'use slopeRatio',
        'use midflameWindSpeed',
        'call update',
    ],
}