export const BehaveConfigs = {
    canopyStructureFrom: 'height-base', // 'height-length', 'height-ratio', 'length-base',
    fuelCuringFrom: 'estimate', // input
    fuelModels: 'two',  // 'one, two, chaparral, aspen, custom, pg
    moistureDeadFuelFrom: 'particles', // particles
    moistureLiveFuelFrom: 'particles', // particles
    midflameWindSpeedFrom: 'estimate', // input
    midflameWsrfFrom: 'estimate', // input
    slopeDirectionFrom: 'slopeUpslope', // slopeAspect, slopeUpslope
    slopeSteepnessFrom: 'slopeMap', // slopeDegrees, slopeMap, slopeRatio
    windDirectionFrom: 'windSourceCompass',    // windBearingDegrees, windSourceCompass, windSourceDegrees
    windSpeedFrom: 'windSpeed10m', // windSpeed20ft
}

export const BehaveRules = {
    canopyStructure: [
        'if canopyStructureFrom height-base',
            'input canopyHeight',
            'input canopyBase',
            'input canopyCover',
            'call updateFromHeightBase',
        'endif',
        'if canopyStructureFrom height-length',
            'input canopyHeight',
            'input canopyLength',
            'input canopyCover',
            'call updateFromHeightLength',
        'endif',
        'if canopyStructureFrom height-ratio',
            'input canopyHeight',
            'input canopyRatio',
            'input canopyCover',
            'call updateFromHeightRatio',
        'endif',
        'if canopyStructureFrom length-base',
            'input canopyLength',
            'input canopyBase',
            'input canopyCover',
            'call updateFromLengthBase',
        'endif',
    ],

    fuelCatalog: [],

    fuelCuring: [
        'if fuelCuringFrom input',
            'input curedHerb',
            'input curedCheatgrass',
            'call updateFromInput',
        'endif',
        'if fuelCuringFrom estimate',
            'input moistureLiveHerb',
            'call updateFromHerbMoisture',
        'endif',
    ],
    
    fuelModels: [
        'use fuelCatalog',
        'input fuelKeyOne',
        'if fuelModels two',
            'input fuelKeyTwo',
        'endif',
        'call updateFromFuelKeys',
    ],
    fuelBeds: [
        'use fuelModels',
        'use fuelCuring',
        'call updateFromFuelModelAndCuring',
    ],
    fuelIgnitions: [
        'use fuelBeds',
        'use moistureLiveFuels',
        'use moistureDeadFuels',
        'call updateFromFuelBedAndMoisture',
    ],
    fireBehaviors: [
        'use fuelIgnitions',
        'use slopeDirection',
        'use windDirection',
        'use slopeSteepness',
        'use midflameWindSpeed',
        'if fuelModels two',
            'input fuelCoverOne',
        'endif',
        'call updateFromWindSlope',
    ],

    midflameWindSpeed: [
        'if midflameWindSpeedFrom input',
            'input midflameWindSpeed',
        'endif',
        'if midflameWindSpeedFrom estimate',
            'use midflameWsrf',
            'use windSpeed',
            'call updateFrom20ftWsrf',
        'endif',
    ],
    midflameWsrf: [
        'if midflameWsrfFrom input',
            'input midflameWsrf',
        'endif',
        'if midflameWsrfFrom estimate',
            'use canopyStructure',
            'use fuelBeds',
            'call updateFromCanopyFuelBed',
        'endif',
    ],
    moistureDeadFuels: [
        'if moistureDeadFuelFrom category',
            'input moistureDeadCategory',
            'call updateFromCategory',
        'endif',
        'if moistureDeadFuelFrom particles',
            'input moistureDead100h',
            'input moistureDead10h',
            'input moistureDead1h',
            'call updateFromParticles',
    ],
    moistureLiveFuels: [
        'if moistureLiveFuelFrom category',
            'input moistureLiveCategory',
            'call updateFromCategory',
        'endif',
        'if moistureLiveFuelFrom particles',
            'input moistureLiveStem',
            'input moistureLiveHerb',
            'call updateFromParticles',
    ],
    slopeDirection: [
        'if slopeDirectionFrom slopeAspect',
            'input slopeAspect',
            'call updateFromSlopeAspect',
        'endif',
        'if slopeDirectionFrom slopeUpslope',
            'input slopeUpslope',
            'call updateFromSlopeUpslope',
        'endif',
    ],
    slopeMap: [
        'input mapScale',
        'input mapContourInterval',
        'input mapContoursCrossed',
        'input mapDistance',
        'call updateSlopeSteepnessFromMap',
    ],
    slopeSteepness : [
        'if slopeSteepnessFrom slopeDegrees',
            'input slopeDegrees',
            'call updateFromSlopeDegrees',
        'endif',
        'if slopeSteepnessFrom slopeMap',
            'use slopeMap',
            'call updateFromSlopeMap',
        'endif',
        'if slopeSteepnessFrom slopeRatio',
            'use slopeRatio',
            'call updateFromSlopeRatio',
        'endif',
    ],
    windDirection: [
        'if windDirectionFrom windBearingDegrees',
            'input windBearingDegrees',
            'call updateFromWindBearingDegrees',
        'endif',
        'if windDirectionFrom windSourceCompass',
            'input windSourceCompass',
            'call updateFromWindSourceCompass',
        'endif',
        'if windDirectionFrom windSourceDegrees',
            'input windSourceDegrees',
            'call updateFromWindSourceDegrees',
        'endif',
    ],
    windSpeed: [
        'if windSpeedFrom windSpeed10m',
            'input windSpeed10m',
            'call updateFromWindSpeed10m',
        'endif',
        'if windSpeedFrom windSpeed20ft',
            'input windSpeed20ft',
            'call updateFromWindSpeed20ft',
        'endif',
    ],
}