export const BehaveConfigs = {
    canopyStructureFrom: 'height-base',
    // 'height-length',
    // 'height-ratio',
    // 'length-base',
    fuelCuringFrom: 'estimate', // input
    fuelMoistureDeadFrom: 'particles', // particles
    fuelMoistureLiveFrom: 'particles', // particles
    midflameWindSpeedFrom: 'estimate', // input
    midflameWsrfFrom: 'estimate', // input
    slopeSteepnessFrom: 'slopeDegrees', // slopeMap, slopeRatio
    windSpeedFrom: 'windSpeed10m', // windSpeed20ft
}
export const BehaveRules = {
    canopyStructure: [
        'if canopyStructureFrom height-base',
            'get self.canopyHeight',
            'get self.canopyBase',
            'get self.canopyCover',
            'call self.updateFromHeightBase',
        'endif',
        'if canopyStructureFrom height-length',
            'get self.canopyHeight',
            'get self.canopyLength',
            'get self.canopyCover',
            'call self.updateFromHeightBase',
        'endif',
        'if canopyStructureFrom height-ratio',
            'get self.canopyHeight',
            'get self.canopyRatio',
            'get self.canopyCover',
            'call self.updateFromHeightBase',
        'endif',
        'if canopyStructureFrom length-base',
            'get self.canopyLength',
            'get self.canopyBase',
            'get self.canopyCover',
            'call self.updateFromHeightBase',
        'endif',
    ],
    fuelCuring: [
        'if fuelCuringFrom input',
            'get self.curedHerb',
            // 'get self.curedCheatgrass',
            // 'collect fuelCuringClasses',
        'endif',
        'if fuelCuringFrom estimate',
            'use moistureLiveHerb',
            'call self.updateFromMoistureLiveHerb',
        'endif',
    ],
    fuelMoisture: [
        'use moistureLiveHerb',
        'use moistureLiveStem',
        'use moistureDead100h',
        'use moistureDead10h',
        'use moistureDead1h',
    ],
    moistureDead1h: [
        'if fuelMoistureDeadFrom particles',
            'get fuelMoisture.self',
        'endif',
        'if fuelMoistureDeadFrom category',
            'get fuelMoisture.moistureDeadCategory',
            'call fuelMoisture.updateFromDeadCategory',
        'endif',
    ],
    moistureDead10h: [
        'if fuelMoistureDeadFrom particles',
            'get fuelMoisture.self',
        'endif',
        'if fuelMoistureDeadFrom category',
            'get fuelMoisture.moistureDeadCategory',
            'call fuelMoisture.updateFromDeadCategory',
        'endif',
    ],
    moistureDead100h: [
        'if fuelMoistureDeadFrom particles',
            'get fuelMoisture.self',
        'endif',
        'if fuelMoistureDeadFrom category',
            'get fuelMoisture.moistureDeadCategory',
            'call fuelMoisture.updateFromDeadCategory',
        'endif',
    ],
    moistureLiveHerb: [
        'if fuelMoistureLiveFrom particles',
            'get fuelMoisture.self',
        'endif',
        'if fuelMoistureLiveFrom category',
            'get fuelMoisture.moistureLiveCategory',
            'call fuelMoisture.updateFromLiveCategory',
        'endif',
    ],
    moistureLiveStem: [
        'if fuelMoistureLiveFrom particles',
            'get fuelMoisture.self',
        'endif',
        'if fuelMoistureLiveFrom category',
            'get fuelMoisture.moistureLiveCategory',
            'call fuelMoisture.updateFromLiveCategory',
        'endif',
    ],
    midflameWindSpeed: [
        'if midflameWindSpeedFrom input',
            'get self.midflameWindSpeed',
        'endif',
        'if midflameWindSpeedFrom estimate',
            'use midflameWsrf',
            'use windSpeed',
            'call self.update',
        'endif',
    ],
    midflameWsrf: [
        'if midflameWsrfFrom input',
            'get self.midflameWsrf',
        'endif',
        'if midflameWsrfFrom estimate',
            'use canopyStructure',
            'use primaryFuelBed',
            'call self.update',
        'endif',
    ],
    slopeSteepness: [
        'if slopeSteepnessFrom slopeDegrees',
            'get self.slopeDegrees slopeDegrees',
            'call self.updateFromSlopeDegrees',
        'endif',
        'if slopeSteepnessFrom slopeMap',
            'use slopeMap',
            'call self.updateFromSlopeMap',
        'endif',
        'if slopeSteepnessFrom slopeRatio',
            'get self.slopeRatio slopeRatio',
            'call self.updateFromSlopeRatio',
        'endif',
    ],
    windSpeed: [
        'if windSpeedFrom windSpeed10m',
            'get self.windSpeed10m',
            'call self.updateFromWindSpeed10m',
        'endif',
        'if windSpeedFrom windSpeed20ft',
            'get self.windSpeed20ft',
            'call self.updateFromWindSpeed20ft',
        'endif',
    ],

    // TBD
    fuelCatalog: [],
    fuelKeys: [
        'get self.primaryFuelKey',
    ],
    primaryFuelModel: [
        'use fuelCatalog',
        'use fuelKeys',
        'call self.makeFuelModel',
    ],
    primaryFuelBed: [
        'use primaryFuelModel',
        'use fuelCuring',
        'call self.makeFuelBed',
    ],
    primaryFuelIgnition: [
        'use primaryFuelBed',
        'use fuelMoisture',
        'call self.makeFuelIgnition',
    ],
    primaryFireBehavior: [
        'use primaryFuelBed',
        'use primaryFuelIgnition',
        'use slopeDirection',
        'use windDirection',
        'use slopeSteepness',
        'use midflameWindSpeed',
        'call self.makeFireBehavior',
    ],
    slopeDirection: [],
    windDirection: [],

}