/**
 * WfbxInputs defines default initial values for all possible Wfbx input parameters.
 */
export class WfbxInputs {
    constructor() {
        this.fuelKey1 = [0]
        this.fuelKey2 = [0]
        this.fuelCover1 = [1]
        this.curedHerb = [0]
        this.moistureDead1h = [1]
        this.moistureDead10h = [1]
        this.moistureDead100h = [1]
        this.moistureDeadCategory = [1]
        this.moistureLiveCategory = [5]
        this.moistureLiveCurable = [5]
        this.moistureLiveHerb = [5]
        this.moistureLiveStem = [5]
        this.slopeAspect = [180]
        this.slopeUpslope = [0]
        this.slopeDegrees = [0]
        this.slopeRatio = [0]
        this.mapScale = [24000]
        this.mapContourInterval = [100]
        this.mapContoursCrossed = [0]
        this.mapDistance = [0]
        this.windSpeed20ft = [0]
        this.windSpeed10m = [0]
        this.windBearingCompass = ['N']
        this.windBearingDegrees = [0]
        this.windSourceCompass = ['S']
        this.windSourceDgerees = [180]
        this.midflameWindSpeed = [0]
        this.midflameWsrf = [1]
        this.canopyHeight = [0]
        this.canopyBase = [0]
        this.canopyCover = [0]
        this.canopyBulkDensity = [0]
        this.canopyHeatContent = [8000]
        this.observedHeadSpreadRate = [0]
        this.observedHeadBearing = [0]
        this.observedHeadFlameLength = [0]
        this.observedLengthWidthRatio = [1]
        this.limitWindSpeedFactor = [true]
        this.limitSpreadRateToWindSpeed = [true]
        this.airTemperature = [77]
        this.elapsedTime = [0]
        this.ignEast = [0]
        this.ignNorth = [0]
        this.angleFromHead = [0]
        this.treeSpecies = ['ABBA']
    }
}
