export class BearingDemo01Model {
    constructor() {
        const distance = 144
        const e = 300
        const n = 300
        this.vectors = [
            {east: e, north: n, bearing: 0, distance},
            {east: e, north: n, bearing: 45, distance},
            {east: e, north: n, bearing: 90, distance},
            {east: e, north: n, bearing: 135, distance},
            {east: e, north: n, bearing: 180, distance},
            {east: e, north: n, bearing: 225, distance},
            {east: e, north: n, bearing: 270, distance},
            {east: e, north: n, bearing: 315, distance},
            {east: -e, north: n, bearing: 0, distance},
            {east: -e, north: n, bearing: 45, distance},
            {east: -e, north: n, bearing: 90, distance},
            {east: -e, north: n, bearing: 135, distance},
            {east: -e, north: n, bearing: 180, distance},
            {east: -e, north: n, bearing: 225, distance},
            {east: -e, north: n, bearing: 270, distance},
            {east: -e, north: n, bearing: 315, distance},
            {east: e, north: -n, bearing: 0, distance},
            {east: e, north: -n, bearing: 45, distance},
            {east: e, north: -n, bearing: 90, distance},
            {east: e, north: -n, bearing: 135, distance},
            {east: e, north: -n, bearing: 180, distance},
            {east: e, north: -n, bearing: 225, distance},
            {east: e, north: -n, bearing: 270, distance},
            {east: e, north: -n, bearing: 315, distance},
            {east: -e, north: -n, bearing: 0, distance},
            {east: -e, north: -n, bearing: 45, distance},
            {east: -e, north: -n, bearing: 90, distance},
            {east: -e, north: -n, bearing: 135, distance},
            {east: -e, north: -n, bearing: 180, distance},
            {east: -e, north: -n, bearing: 225, distance},
            {east: -e, north: -n, bearing: 270, distance},
            {east: -e, north: -n, bearing: 315, distance},
            {east: 0, north: 0, bearing: 0, distance},
            {east: 0, north: 0, bearing: 45, distance},
            {east: 0, north: 0, bearing: 90, distance},
            {east: 0, north: 0, bearing: 135, distance},
            {east: 0, north: 0, bearing: 180, distance},
            {east: 0, north: 0, bearing: 225, distance},
            {east: 0, north: 0, bearing: 270, distance},
            {east: 0, north: 0, bearing: 315, distance},
            {east: -300, north: -50, bearing: 0, distance: 100},
            {east: -300, north: -50, bearing: 45, distance: 100},
            {east: -300, north: -50, bearing: 90, distance: 100},
            {east: -300, north: -50, bearing: 135, distance: 100},
            {east: -300, north: -50, bearing: 180, distance: 100},
            {east: -300, north: -50, bearing: 225, distance: 100},
            {east: -300, north: -50, bearing: 270, distance: 100},
            {east: -300, north: -50, bearing: 315, distance: 100},
            {east: -50, north: 250, bearing: 0, distance: 100},
            {east: -50, north: 250, bearing: 45, distance: 100},
            {east: -50, north: 250, bearing: 90, distance: 100},
            {east: -50, north: 250, bearing: 135, distance: 100},
            {east: -50, north: 250, bearing: 180, distance: 100},
            {east: -50, north: 250, bearing: 225, distance: 100},
            {east: -50, north: 250, bearing: 270, distance: 100},
            {east: -50, north: 250, bearing: 315, distance: 100},
        ]
    }
}