export const Rules = {
    surfaceFire: [
        'if surfaceFireModule active',
            'apply fireBehaviors',
            'if fireSizeModule linkedSurface',
                'apply fireSize',
                'if headVectorModule active',
                    'apply headVectorModule',
                'endif',
                'if backVectorModule active',
                    'apply backVectorModule',
                'endif',
                'if rightVectorModule active',
                    'apply rightVectorModule',
                'endif',
                'if leftVectorModule active',
                    'apply leftVectorModule',
                'endif',
                'if betaVectorModule active',
                    'apply betaVectorModule',
                'endif',
                'if beta6VectorModule active',
                    'apply beta6VectorModule',
                'endif',
                'if psiVectorModule active',
                    'apply psiVectorModule',
                'endif',
                'if thetaVectorModule active',
                    'apply thetaVectorModule',
                'endif',
            'endif',
        'endif',
    ],

    deadFuelMoistures: [
        'if deadFuelMoisturesBy particle',
            'next fuelMoistures.dead100h',
            'next fuelMoistures.dead10h',
            'next fuelMoistures.dead1h',
        'elseif deadFuelMoisturesBy category',
            'next fuelMoistures.deadCategory',
            'call updateFromCategory',
        'endif',
    ],

    fuelCuring: [
        'if fuelCuringFrom input',
            'next fuelCuring.curedHerb',
            'next fuelCuring.curedCheatgrass',
        'elseif fuelCuringFrom fuelMoistureLiveHerb',
            'next fuelMoistures.liveHerb',
            'call fuelCuring.updateFromLiveHerbMoisture',
        'endif',
    ],
    fuelCatalog: [
        // create the FuelCatalog and update its curingClasses and moistureClasses
        'call fuelCatalog.make',
        'if activeCrownFireModule active',
            // create activeCrownFire: {fuelModel, fuelBed}
            'call activeCrownFire.updateFuelModel',
            'call activeCrownFire.updateFuelBed',
        'endif',
    ],
    fuelModels: [
        'apply fuelCatalog',
        'if fuelModels one',
            'next fuelKey.one',
        'elseif fuelModels two',
            'next fuelKey.one',
            'next fuelKey.two',
        'endif',
        // create new fuelModels = {one, two, curingClasses,moistureClasses}
        'call fuelModels.updateFromFuelKeys',
    ],
    fuelBeds: [
        'apply fuelModels',
        'apply fuelCuring',
        // create new fuelBeds = {one, two}
        'call fuelBeds.updateFromFuelModelsAndCuring'
    ],
    fuelIgnitions: [
        'apply fuelBeds',
        'apply liveFuelMoistures',
        'apply deadFuelMoistures',
        // create new fuelIgnitions = {one, two}
        'call fuelIgnitions.updateFromFuelMoistures',
        'if activeCrownFireModule active',
            'call activeCrownFire.updateFuelIgnition',
        'endif',
    ],
    fireBehaviors: [
        'apply fuelBeds',
        'apply fuelIgnitions',
        'apply slopeDirection',
        'apply windDirection',
        'apply slopeSteepness',
        'apply midflameWindSpeed',
        'call fireBehaviors.updateFireBehavior',
        'if activeCrownFireModule active',
            'call activeCrownFire.updateFireBehavior',
        'endif',
    ],
    fireEllipse: [
        'if fireSizeModule standAlone',
            'next observedFire.headingSpreadRate',
            'next observedFire.bearing',
            'next observedFire.lengthWidthRatio',
            'next observedFire.flameLength',
            'call fireEllipse.updateFromObservedFire()',
        'else',
            'apply fireBehaviors',
            'call fireEllipse.updateFromSurfaceFire',
        'endif',
    ],
    fireSize: [
        'apply fireEllipse',
        'next fireSize.ignEast',
        'next fireSize.ignNorth',
        'next fireSize.elapsedTime',
        'call fireSize.updateFromElapsedTime',
    ],
    headVectorModule: [
        'call fireVectors.updateHeadVector',
    ],
    backVectorModule: [
        'call fireVectors.updateBackVector',
    ],
    rightVectorModule: [
        'call fireVectors.updateRightVector',
    ],
    leftVectorModule: [
        'call fireVectors.updateLeftVector',
    ],
    betaVectorModule: [
        'next fireVectors.angleFromHead',
        'call fireVectors.updateBetaVector',
    ],
    beta6VectorModule: [
        'next fireVectors.angleFromHead',
        'call fireVectors.updateBeta6Vector',
    ],
    psiVectorModule: [
        'next fireVectors.angleFromHead',
        'call fireVectors.updatePsiVector',
    ],
    thetaVectorModule: [
        'next fireVectors.angleFromHead',
        'call fireVectors.updateThetaVector',
    ],
    liveFuelMoistures: [
        'if liveFuelMoisturesBy particle',
            'next fuelMoistures.liveStem',
            'next fuelMoistures.liveHerb',
        'elseif liveFuelMoisturesBy category',
            'next fuelMoistures.liveCategory',
            'call updateFromCategory',
        'endif',
    ],
    midflameWindSpeed: [
        'if midflameWindSpeedFrom input',
            'next midflameWindSpeed.midflameWindSpeed',
        'elseif midflameWindSpeedFrom estimate',
            'apply midflameWsrf',
            'apply windSpeed',
            'call midflameWindSpeed.updateFromWsrfAnd20ftWind',
        'endif',
    ],
    midflameWsrf: [
        'if midflameWsrfFrom input',
            'next midflameWsrf.midflameWsrf',
        'elseif midflameWsrfFrom canopyAndFuelBed',
            'apply canopyStructure',
            'apply fuelBeds',
            'call midflameWsrf.updateFromCanopyAndFuelBed',
        'endif',
    ],
    canopyStructure: [
        'if canopyStructureFrom height-base',
            'next canopy.height',
            'next canopy.base',
            'call canopy.updateFromHeightBase',
        'elseif canopyStructureFrom height-length',
            'next canopy.height',
            'next canopy.length',
            'call canopy.updateFromHeightLength',
        'elseif canopyStructureFrom height-ratio',
            'next canopy.height',
            'next canopy.ratio',
            'call canopy.updateFromHeightRatio',
        'elseif canopyStructureFrom length-base',
            'next canopy.length',
            'next canopy.base',
            'call canopy.updateFromLengthBase',
        'endif',
    ],
    canopyFuel: [
        'next canopy.bulkDensity',
        'next canopy.heatContent',
        'call canopy.updateFuel',
    ],
    slopeDirection: [
        'if slopeDirectionFrom slopeAspect',
            'next slope.direction.aspect',
            'call slope.updateDirectionFromAspect',
        'elseif slopeDirectionFrom slopeUpslope',
            'next slope.direction.upslope',
            'call slope.updateDirectionFromUpslope',
        'endif',
    ],
    slopeMap: [
        'next slopeMap.scale',
        'next slopeMap.contourInterval',
        'next slopeMap.contoursCrossed',
        'next slopeMap.distance',
        'call slopeMap.updateSlopeSteepness',
    ],
    slopeSteepness: [
        'if slopeSteepnessFrom slopeDegrees',
            'next slope.steepness.degrees',
            'call slope.updateSteepnessFromDegrees',
        'elseif slopeSteepnessFrom slopeMap',
            'apply slopeMap',
            'call slope.updateSteepnessFromMap',
        'elseif slopeSteepnessFrom slopeRatio',
            'next slope.steepness.ratio',
            'call slope.updateSteepnessFromRatio',
        'endif',
    ],
    windDirection: [
        'if windDirectionFrom windBearingDegrees',
            'next wind.direction.bearing',
            'call wind.updateDirectionFromBearing',
        'elseif windDirectionFrom windSourceDegrees',
            'next wind.direction.sourceDegrees',
            'call wind.updateDirectionFromUpslope',
        'elseif windDirectionFrom windSourceCompass',
            // N, NNE, NE, ENE, E, ESE, SE, SSE, S, SSW, SW, WSW, W, WNW, NW, NNW
            'next wind.direction.sourceCompass',
            'call wind.updateDirectionFromCompass',
        'endif',
    ],
    windSpeed: [
        'if windSpeedFrom windSpeed10m',
            'next wind.speed.at10m',
            'call wind.updateFrom10m',
            // TRY calling State methods instead of module methods ???
            // 'next windSpeed.at20ft windSpeed20ft',
            // 'call updateWindSpeedFrom10m',
        'elseif windSpeedFrom windSpeed20ft',
            'next wind.speed.at20ft',
            'call wind.updateFrom20ft',
            // TRY calling State methods instead of module methods ???
            // 'next windSpeed.at20ft windSpeed20ft',
            // 'call updateWindSpeedFrom20ft',
        'endif'
    ],
}