<script>
    import {EventfulSvg} from '$lib/index.js'
    import {ViewportDemo} from './ViewportDemo.js'

    // Viewport SVG dimenisions
    let width = $state(400)
    let height = $state(400)

    // ViewportDemo is a class that draws the image and maintains its state
    // We only need to specify the SVG width, height here,
    // and let the Viewport-derived class define all the other properties
    let viewport = $derived(new ViewportDemo(width, height))
    let content = $derived(viewport.drawSvg())

    function handler(e) {
        if (viewport.handleEvent(e)) content = viewport.drawSvg()
    }
</script>

<div class='ml-4 text-2xl'>EventfulViewport Demo</div>

<div class='ml-4 mt-6 text-normal'>
    Below is a {width} x {height} image generated by a EventfulViewport 
    derived class that responds to pan and zoom events and keystrokes.
</div>

<div class='ml-4 mt-4'>
    <EventfulSvg {width} {height} {content} {handler}/>
</div>
