export const FbfmFuelGroups = {
    '13': {
        groupKey: '13',
        fuelKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13'],
        spriteFill: '#FB7185', // rose-400'},
        active: "bg-rose-400 focus:ring-rose-300",
        inactive: "bg-gray-100 text-gray-700",},
    gr: {
        groupKey: 'gr',
        fuelKeys: ['gr1', 'gr2', 'gr3', 'gr4', 'gr5', 'gr6',  'gr7', 'gr8', 'gr9'],
        spriteFill: '#FFA14A', // orange-400
        active: "bg-orange-400 focus:ring-orange-300",
        inactive: "bg-gray-100 text-gray-700",},
    gs: {
        groupKey: 'gs',
        fuelKeys: ['gs1', 'gs2', 'gs3', 'gs4'],
        active: "bg-lime-400 focus:ring-lime-300",
        inactive: "bg-gray-100 text-gray-700",
        spriteFill: '#A3E635',}, // lime-400
    sh: {
        groupKey: 'sh',
        fuelKeys: ['sh1', 'sh2', 'sh3', 'sh4', 'sh5',  'sh6', 'sh7', 'sh8', 'sh9'],
        active: "bg-green-400 focus:ring-green-300",
        inactive: "bg-gray-100 text-gray-700",
        spriteFill: '#A4DE80',},    // green-400
    tu: {
        groupKey: 'tu',
        fuelKeys: ['tu1', 'tu2', 'tu3', 'tu4', 'tu5'],
        active: "bg-emerald-400 focus:ring-emerald-300",
        inactive: "bg-gray-100 text-gray-700",
        spriteFill: '#34D399',},    // emerald-400
    tl: {
        groupKey: 'tl',
        fuelKeys: ['tl1', 'tl2', 'tl3', 'tl4', 'tl5', 'tl6', 'tl7', 'tl8', 'tl9'],
        active: "bg-teal-400 focus:ring-teal-30",
        inactive: "bg-gray-100 text-gray-700",
        spriteFill: '#2DD4BF',},    // teal-400
    sb: {
        groupKey: 'sb',
        fuelKeys: ['sb1', 'sb2', 'sb3', 'sb4'],
        active: "bg-red-400 focus:ring-red-300",
        inactive: "bg-gray-100 text-gray-700",
        spriteFill: '#FF6467',},    // red-400
}
export const FbfmFuelStyles = {
    '1': {...FbfmFuelGroups[13]},
    '2': {...FbfmFuelGroups[13]},
    '3': {...FbfmFuelGroups[13]},
    '4': {...FbfmFuelGroups[13]},
    '5': {...FbfmFuelGroups[13]},
    '6': {...FbfmFuelGroups[13]},
    '7': {...FbfmFuelGroups[13]},
    '8': {...FbfmFuelGroups[13]},
    '9': {...FbfmFuelGroups[13]},
    '10': {...FbfmFuelGroups[13]},
    '11': {...FbfmFuelGroups[13]},
    '12': {...FbfmFuelGroups[13]},
    '13': {...FbfmFuelGroups[13]},
    'gr1': {...FbfmFuelGroups['gr']},
    'gr2': {...FbfmFuelGroups['gr']},
    'gr3': {...FbfmFuelGroups['gr']},
    'gr4': {...FbfmFuelGroups['gr']},
    'gr5': {...FbfmFuelGroups['gr']},
    'gr6': {...FbfmFuelGroups['gr']},
    'gr7': {...FbfmFuelGroups['gr']},
    'gr8': {...FbfmFuelGroups['gr']},
    'gr9': {...FbfmFuelGroups['gr']},
    'gs1': {...FbfmFuelGroups['gs']},
    'gs2': {...FbfmFuelGroups['gs']},
    'gs3': {...FbfmFuelGroups['gs']},
    'gs4': {...FbfmFuelGroups['gs']},
    'sh1': {...FbfmFuelGroups['sh']},
    'sh2': {...FbfmFuelGroups['sh']},
    'sh3': {...FbfmFuelGroups['sh']},
    'sh4': {...FbfmFuelGroups['sh']},
    'sh5': {...FbfmFuelGroups['sh']},
    'sh6': {...FbfmFuelGroups['sh']},
    'sh7': {...FbfmFuelGroups['sh']},
    'sh8': {...FbfmFuelGroups['sh']},
    'sh9': {...FbfmFuelGroups['sh']},
    'tu1': {...FbfmFuelGroups['tu']},
    'tu2': {...FbfmFuelGroups['tu']},
    'tu3': {...FbfmFuelGroups['tu']},
    'tu4': {...FbfmFuelGroups['tu']},
    'tu5': {...FbfmFuelGroups['tu']},
    'tl1': {...FbfmFuelGroups['tl']},
    'tl2': {...FbfmFuelGroups['tl']},
    'tl3': {...FbfmFuelGroups['tl']},
    'tl4': {...FbfmFuelGroups['tl']},
    'tl5': {...FbfmFuelGroups['tl']},
    'tl6': {...FbfmFuelGroups['tl']},
    'tl7': {...FbfmFuelGroups['tl']},
    'tl8': {...FbfmFuelGroups['tl']},
    'tl9': {...FbfmFuelGroups['tl']},
    'sb1': {...FbfmFuelGroups['sb']},
    'sb2': {...FbfmFuelGroups['sb']},
    'sb3': {...FbfmFuelGroups['sb']},
    'sb4': {...FbfmFuelGroups['sb']},
}
